### ISSUE TITLE
[예시] RDB란 무엇인가?

### ISSUE THREAD

**Issue by egg528** [10000-Bagger/free-topic-study#1]
# 내용~~

**Comment by egg528** [comment]
@deepbig @binary-ho 
LABELS로 카테고리(DB, Network 등등) 설정하고 이렇게 ISSUE로 글 올리는 건 어때?

**Comment by egg528** [comment]
근데 Assignees / Labels / Projects들 설정이 안 됩니다~~

**Comment by deepbig** [comment]
LABELS로 카테고리 좋아~~~!

근데 PR 말고 이슈?? PR로 다음날 아침까지 어푸루부 받는 건 어때~~~~~??

**Comment by egg528** [comment]
옛날에 사용하던 방식인데 나는 글을 다시 보게 된다면 댓글까지 같이 보고 싶을 것 같아서 아래 링크처럼 ISSUE로 정리하면 어떨까 했어!
- https://github.com/egg528/egg528/issues

**Comment by deepbig** [comment]
오오오 근데 PR도 댓글 볼 수 있지 않아??
이런 방식은 어때?? https://github.com/Seogeurim/CS-study/tree/main 이것처럼 우리도 자유 주제로 카테고리 만들어서 같이 작업하는 것도 재밌을 것 같아~!!!! @@ 
오늘 회의 끝나고 뭐가 좋을지 잠깐 이야기해보자~~~~~~~!ㅎㅎㅎㅎ

**Comment by egg528** [comment]
서로 생각하는 진행 방식이 다른 것 같아서 이따 얘기해보는 게 좋을 것 같다!

**Comment by binary-ho** [comment]
나도 대댓글 달기 + ㄹㅇ 파일 생성 같은거 때문에 PR로 생각했었는데, 이따 대화 고고!

그리고 우석이 권한은 Admin일단 초대 해놨는데, 초대 Awaiting 중이라고 뜨네?? 메일 한번 확인해보실?
홍석이는 받았어

**Comment by egg528** [comment]
@binary-ho 확인했습니다~ 👍
